import {Store} from './store';

export const BAndH: Store = {
  backoffStatusCodes: [403, 429],
  currency: '$',
  labels: {
    inStock: {
      container: 'div[data-selenium="addToCartSection"]',
      text: ['add to cart'],
    },
    maxPrice: {
      container: 'div[data-selenium="pricingPrice"]',
      euroFormat: false,
    },
    outOfStock: {
      container: 'button[data-selenium="notifyAvailabilityButton"]',
      text: ['notify when available'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.bhphotovideo.com/c/product/1452927-REG/evga_06g_p4_2063_kr_geforce_rtx_2060_xc.html',
    },
    {
      brand: 'gigabyte',
      model: 'aero',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875711-REG/gigabyte_gv_n5080aero_oc_16gd_geforce_rtx_5080_aero.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875712-REG/gigabyte_gv_n5080aorus_m_16gd_geforce_rtx_5080_master.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master 24g',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875713-REG/gigabyte_gv_n5080aorusm_ice_16gd_geforce_rtx_5080_master.html',
    },
    {
      brand: 'gigabyte',
      model: 'windforce',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875716-REG/gigabyte_gv_n5080wf3oc_16gd_geforce_rtx_5080_windforce.html',
    },
    {
      brand: 'gigabyte',
      model: 'windforce v2',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1872787-REG/gigabyte_gv_n5080wf3_16gd_geforce_rtx_5080_windforce.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1872786-REG/gigabyte_gv_n5080gaming_oc_16gd_geforce_rtx_5080_gaming.html',
    },
    {
      brand: 'asus',
      model: 'prime',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1874876-REG/asus_prime_rtx5080_16g_geforce_rtx_5080_prime.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1872330-REG/asus_tuf_rtx5080_o16g_gaming_geforce_rtx_5080_tuf.html',
    },
    {
      brand: 'asus',
      model: 'astral',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1872329-REG/asus_rog_astral_rtx5080_o16g_gaming_republic_of_gamers_astral.html',
    },
    {
      brand: 'asus',
      model: 'prime',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1872328-REG/asus_prime_rtx5080_o16g_geforce_rtx_5080_prime.html',
    },
    {
      brand: 'pny',
      model: 'argb',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1874646-REG/pny_vcg508016tfxxpb1_o_nvidia_geforce_rtx_5080.html',
    },
    {
      brand: 'pny',
      model: 'triple',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1874645-REG/pny_vcg508016tfxpb1_o_nvidia_geforce_rtx_5080.html',
    },
    {
      brand: 'msi',
      model: 'vanguard',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875464-REG/msi_g5080_16vgsl_geforce_rtx_5080_vanguard.html',
    },
    {
      brand: 'msi',
      model: 'vanguard',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875463-REG/msi_g5080_16vgs_geforce_rtx_5080_vanguard.html',
    },
    {
      brand: 'msi',
      model: 'ventus',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875459-REG/msi_g5080_16i3c_geforce_rtx_5080_inspire.html',
    },
    {
      brand: 'msi',
      model: 'ventus',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875462-REG/msi_g5080_16v3cp_geforce_rtx_5080_ventus.html',
    },
    {
      brand: 'msi',
      model: 'gaming oc',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875458-REG/msi_g5080_16gtcw_geforce_rtx_5080_gaming.html',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875461-REG/msi_g5080_16sps_geforce_rtx_5080_suprim.html',
    },
    {
      brand: 'msi',
      model: 'suprim liquid x',
      series: '5080',
      url: 'https://www.bhphotovideo.com/c/product/1875460-REG/msi_g5080_16sls_geforce_rtx_5080_suprim.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875468-REG/msi_g5090_32v3c_geforce_rtx_5090_ventus.html',
    },
    {
      brand: 'msi',
      model: 'gaming',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875465-REG/msi_g5090_32gtc_geforce_rtx_5090_gaming.html',
    },
    {
      brand: 'msi',
      model: 'suprim liquid x',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875466-REG/msi_g5090_32sls_geforce_rtx_5090_suprim.html',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875467-REG/msi_g5090_32sps_geforce_rtx_5090_suprim.html',
    },
    {
      brand: 'msi',
      model: 'vanguard',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875469-REG/msi_g5090_32vgs_geforce_rtx_5090_vanguard.html',
    },
    {
      brand: 'msi',
      model: 'vanguard',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875470-REG/msi_g5090_32vgsl_geforce_rtx_5090_vanguard.html',
    },
    {
      brand: 'gigabyte',
      model: 'windforce',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875722-REG/gigabyte_gv_n5090wf3oc_32gd_geforce_rtx_5090_windforce.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875721-REG/gigabyte_gv_n5090gaming_oc_32gd_geforce_rtx_5090_gaming.html',
    },
    {
      brand: 'gigabyte',
      model: 'waterforce',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875720-REG/gigabyte_gv_n5090aorusx_wb_32gd_geforce_rtx_5090_aorus.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875719-REG/gigabyte_gv_n5090aorusx_w_32gd_geforce_rtx_5080_aorus.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875718-REG/gigabyte_gv_n5090aorusm_ice_32gd_geforce_rtx_5090_master.html',
    },
    {
      brand: 'asus',
      model: 'astral',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875529-REG/asus_rog_astral_rtx5090_o32g_gaming_geforce_rtx_5090_republic.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1875530-REG/asus_tuf_rtx5090_32g_gaming_geforce_rtx_5090_tuf.html',
    },
    {
      brand: 'pny',
      model: 'triple',
      series: '5090',
      url: 'https://www.bhphotovideo.com/c/product/1874647-REG/pny_vcg509032tfxpb1_o_nvidia_geforce_rtx_5090.html',
    }
  ],
  name: 'bandh',
};
